trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-west-2' 
  BUCKET_NAME: 'hello-app-deploy'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build Vite App'

  - task: AmazonWebServices.aws-vsts-tools.AWSS3Upload@1
    inputs:
      awsCredentials: 'AWS-DevOps-Creds' 
      regionName: '$(AWS_REGION)'
      bucketName: '$(BUCKET_NAME)'
      sourceFolder: 'dist'
      globExpressions: '**'
      createBucket: false
    displayName: 'Upload to S3'
